<?php
/**
 * Aceextensions Extensions
 *
 * @category   Aceextensions
 * @package    Aceextensions_B2bRegistration
 * @author     Durga Shankar Gupta (dsguptas@gmail.com)
 * @copyright  Copyright (c) 2019 Aceextensions Extensions ( http://aceextensions.com )
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Create account form template
 *
 * @var \Aceextensions\B2bRegistration\Block\CustomerRegister $block
 */
?>
<?php
$prefix = $block->getPrefixField();
$middle = $block->getMiddleField();
$suffix = $block->getSuffixField();
$prefixDefault = $block->getPreffixFieldDefault();
$suffixDefault = $block->getSuffixFieldDefault();
$dobDefault = $block->getDobFieldDefault();
$taxDefault = $block->getTaxFieldDefault();
$genderDefault = $block->getGenderFieldDefault();
$telephoneDefault = $block->getTelephoneFieldDefault();
$companyDefault = $block->getCompanyFieldDefault();
$faxDefault = $block->getFaxFieldDefault();
$compareMagentoVersion = $block->getMagentoVersion();
$vatDefault = $block->getVatFieldDefault();
?>
<?php echo $block->getChildHtml('form_fields_before') ?>
<?php /* Extensions placeholder */ ?>
<?php echo $block->getChildHtml('customer.form.register.extra') ?>
<form class="form create account form-create-account" action="<?php echo $block->escapeUrl($block->getPostAction()) ?>"
      method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
    <?php /* @noEscape */
    echo $block->getBlockHtml('formkey'); ?>
    <fieldset class="fieldset create info">
        <legend class="legend"><span><?php echo $block->escapeHtml(__('Personal Information')) ?></span></legend>
        <br>
        <input type="hidden" name="success_url" value="<?php echo $block->escapeUrl($block->getSuccessUrl()) ?>">
        <input type="hidden" name="error_url" value="<?php echo $block->escapeUrl($block->getErrorUrl()) ?>">
        <?php if ($prefixDefault == "req" || $prefix || $middle || $suffix || $suffixDefault == "req") : ?>
        <div class="field required fullname">
            <div class="control">
                <fieldset class="fieldset fieldset-fullname">
                    <div class="fields">
                        <?php endif; ?>
                        <?php if ($prefixDefault == "req" || $prefix): ?>
                            <div class="field field-name-prefix<?php if ($prefixDefault == "req") echo ' required' ?>">
                                <label class="label" for="prefix">
                                    <span><?php echo __('Name Prefix') ?></span>
                                </label>
                                <div class="control">
                                    <?php if ($block->getPrefixOptions() === false): ?>
                                        <input type="text" id="prefix" name="prefix" value="" title="Name Prefix"
                                               class="" <?php if ($prefix == "req") echo ' data-validate="{required:true}"' ?>>
                                    <?php else: ?>
                                        <select id="prefix" name="prefix" title="Name Prefix"
                                                class="" <?php if ($prefixDefault == "req") echo 'data-validate="{required:true}"' ?>>
                                            <?php foreach ($block->getPrefixOptions() as $option): ?>
                                                <option value="<?= $block->escapeHtml($option) ?>">
                                                    <?= $block->escapeHtml(__($option)) ?>
                                                </option>
                                            <?php endforeach; ?>
                                            <option value="" selected="selected"></option>
                                        </select>
                                    <?php endif; ?>
                                </div>
                            </div>
                        <?php endif; ?>
                        <div class="field field-name-firstname required">
                            <label class="label" for="firstname">
                                <span><?php echo __('First Name') ?></span>
                            </label>
                            <div class="control">
                                <input type="text" id="firstname" name="firstname" value="" title="First Name"
                                       class="input-text required-entry">
                            </div>
                        </div>
                        <?php if ($middle): ?>
                            <div class="field field-name-middlename">
                                <label class="label" for="middlename">
                                    <span><?php echo __('Middle Name/Initial') ?></span>
                                </label>

                                <div class="control">
                                    <input type="text" id="middlename" name="middlename" value=""
                                           title="Middle Name/Initial" class="input-text">
                                </div>
                            </div>
                        <?php endif; ?>
                        <div class="field field-name-lastname required">
                            <label class="label" for="lastname">
                                <span><?php echo __('Last Name') ?></span>
                            </label>
                            <div class="control">
                                <input type="text" id="lastname" name="lastname" value="" title="Last Name"
                                       class="input-text required-entry">
                            </div>
                        </div>
                        <?php if ($suffixDefault == "req" || $suffix): ?>
                            <div class="field field-name-suffix<?php if ($suffixDefault == "req") echo ' required' ?>">
                                <label class="label" for="suffix">
                                    <span><?php echo __('Name Suffix') ?></span>
                                </label>
                                <div class="control">
                                    <?php if ($block->getSuffixOptions() === false): ?>
                                        <input type="text" id="suffix" name="suffix" value="" title="Name Suffix"
                                               class="" <?php if ($suffix == "req") echo ' data-validate="{required:true}"' ?>>
                                    <?php else: ?>
                                        <select id="suffix" name="suffix" title="Name Suffix"
                                                class="" <?php if ($suffixDefault == "req") echo 'data-validate="{required:true}"' ?>>
                                            <?php foreach ($block->getSuffixOptions() as $option): ?>
                                                <option value="<?= $block->escapeHtml($option) ?>">
                                                    <?= $block->escapeHtml(__($option)) ?>
                                                </option>
                                            <?php endforeach; ?>
                                            <option value="" selected="selected"></option>
                                        </select>
                                    <?php endif; ?>
                                </div>
                            </div>
                        <?php endif; ?>
                        <?php if ($prefixDefault == "req" || $prefix || $middle || $suffix || $suffixDefault == "req"): ?>
                    </div>
                </fieldset>
            </div>
        </div>
    <?php endif; ?>

        <?php if ($block->isNewsletterEnabled()): ?>
            <div class="field choice newsletter">
                <input type="checkbox" name="is_subscribed"
                       title="<?php echo $block->escapeHtml(__('Sign Up for Newsletter')) ?>" value="1"
                       id="is_subscribed"<?php if ($block->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?>
                       class="checkbox">
                <label for="is_subscribed"
                       class="label"><span><?php echo $block->escapeHtml(__('Sign Up for Newsletter')) ?></span></label>
            </div>
            <?php /* Extensions placeholder */ ?>
            <?php echo $block->getChildHtml('customer.form.register.newsletter') ?>
        <?php endif ?>

        <?php if ($dobDefault == "req" || $block->getDateField()): ?>
            <?php echo $block->getChildHtml('aceextensions.register.dob') ?>
        <?php endif ?>

        <?php if ($taxDefault == "req" || $block->getTaxField()): ?>
            <?php echo $block->getChildHtml('aceextensions.register.taxvat') ?>
        <?php endif ?>

        <?php if ($genderDefault == "req" || $block->getGenderField()): ?>
            <?php echo $block->getChildHtml('aceextensions.register.gender') ?>
        <?php endif ?>
    </fieldset>

    <?php
    $enableAddressField = $block->getAddressField();
    if ($enableAddressField):
        $block->setShowAddressFields(true);
        if ($block->getShowAddressFields()):
            ?>
            <fieldset class="fieldset address">
                <legend class="legend"><span><?php echo $block->escapeHtml(__('Address Information')) ?></span></legend>
                <br>
                <input type="hidden" name="create_address" value="1"/>

                <?php if ($companyDefault || $compareMagentoVersion): ?>
                    <div class="field company <?php if ($companyDefault == "req") echo "required" ?>">
                        <label for="company" class="label"><span><?php echo $block->escapeHtml(__('Company')) ?></span></label>
                        <div class="control">
                            <input type="text" name="company" id="company"
                                   value="<?php echo $block->escapeHtml($block->getFormData()->getCompany()) ?>"
                                   title="<?php echo $block->escapeHtml(__('Company')) ?>"
                                   class="input-text <?php if ($companyDefault == "req") echo "required-entry" ?>">
                        </div>
                    </div>
                <?php endif; ?>

                <?php if ($telephoneDefault || $compareMagentoVersion): ?>
                    <div class="field telephone <?php if ($telephoneDefault == "req" || $compareMagentoVersion) echo "required" ?>">
                        <label for="telephone"
                               class="label"><span><?php echo $block->escapeHtml(__('Phone Number')) ?></span></label>
                        <div class="control">
                            <input type="text" name="telephone" id="telephone"
                                   value="<?php echo $block->escapeHtml($block->getFormData()->getTelephone()) ?>"
                                   title="<?php echo $block->escapeHtml(__('Phone Number')) ?>"
                                   class="input-text <?php if ($telephoneDefault == "req" || $compareMagentoVersion) echo "required-entry" ?>">
                        </div>
                    </div>
                <?php endif; ?>

                <?php if ($faxDefault || $compareMagentoVersion): ?>
                    <div class="field fax <?php if ($faxDefault == "req") echo "required" ?>">
                        <label for="fax" class="label"><span><?php echo $block->escapeHtml(__('Fax')) ?></span></label>
                        <div class="control">
                            <input type="text" name="fax" id="fax" value=""
                                   title="<?php echo $block->escapeHtml(__('Fax')) ?>"
                                   class="input-text <?php if ($faxDefault == "req") echo "required-entry" ?>">
                        </div>
                    </div>
                <?php endif; ?>

                <div class="field street required">
                    <label for="street_1"
                           class="label"><span><?php echo $block->escapeHtml(__('Street Address')) ?></span></label>
                    <div class="control">
                        <input type="text" name="street[]"
                               value="<?php echo $block->escapeHtml($block->getFormData()->getStreet(0)) ?>"
                               title="<?php echo $block->escapeHtml(__('Street Address')) ?>" id="street_1"
                               class="input-text required-entry">
                        <div class="nested">
                            <?php $streetCount = $block->getStressCount(); ?>
                            <?php for ($_i = 2, $_n = $streetCount; $_i <= $_n; $_i++): ?>
                                <div class="field additional">
                                    <label class="label" for="street_<?php /* @escapeNotVerified */
                                    echo $_i ?>">
                                        <span><?php echo $block->escapeHtml(__('Address')) ?></span>
                                    </label>
                                    <div class="control">
                                        <input type="text" name="street[]"
                                               value="<?php echo $block->escapeHtml($block->getFormData()->getStreetLine($_i - 1)) ?>"
                                               title="<?php echo $block->escapeHtml(__('Street Address %1', $_i)) ?>"
                                               id="street_<?php /* @escapeNotVerified */
                                               echo $_i ?>" class="input-text">
                                    </div>
                                </div>
                            <?php endfor; ?>
                        </div>
                    </div>
                </div>

                <div class="field required">
                    <label for="city" class="label"><span><?php echo $block->escapeHtml(__('City')) ?></span></label>
                    <div class="control">
                        <input type="text" name="city"
                               value="<?php echo $block->escapeHtml($block->getFormData()->getCity()) ?>"
                               title="<?php echo $block->escapeHtml(__('City')) ?>" class="input-text required-entry"
                               id="city">
                    </div>
                </div>

                <div class="field region required">
                    <label for="region_id"
                           class="label"><span><?php echo $block->escapeHtml(__('State/Province')) ?></span></label>
                    <div class="control">
                        <select id="region_id" name="region_id"
                                title="<?php echo $block->escapeHtml(__('State/Province')) ?>" class="validate-select"
                                style="display:none;">
                            <option value=""><?php echo $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                        </select>
                        <input type="text" id="region" name="region"
                               value="<?php echo $block->escapeHtml($block->getRegion()) ?>"
                               title="<?php echo $block->escapeHtml(__('State/Province')) ?>" class="input-text"
                               style="display:none;">
                    </div>
                </div>

                <div class="field zip required">
                    <label for="zip" class="label"><span><?php echo $block->escapeHtml(__('Zip/Postal Code')) ?></span></label>
                    <div class="control">
                        <input type="text" name="postcode"
                               value="<?php echo $block->escapeHtml($block->getFormData()->getPostcode()) ?>"
                               title="<?php echo $block->escapeHtml(__('Zip/Postal Code')) ?>" id="zip"
                               class="input-text validate-zip-international">
                    </div>
                </div>

                <div class="field country required">
                    <label for="country"
                           class="label"><span><?php echo $block->escapeHtml(__('Country')) ?></span></label>
                    <div class="control">
                        <?php echo $block->getCountryHtmlSelect() ?>
                    </div>
                </div>
                <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes'); ?>
                <?php if ($addressAttributes): ?>
                    <?php $addressAttributes->setEntityType('customer_address'); ?>
                    <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]'); ?>
                    <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address'); ?>
                    <?php echo $addressAttributes->setShowContainer(false)->toHtml() ?>
                <?php endif; ?>

                <?php if ($vatDefault): ?>
                    <div class="field vat_id">
                        <label for="vat_id"
                               class="label"><span><?php echo $block->escapeHtml(__('Vat Number')) ?></span></label>
                        <div class="control">
                            <input type="text" name="vat_id" id="vat_id" value=""
                                   title="<?php echo $block->escapeHtml(__('Vat Number')) ?>" class="input-text">
                        </div>
                    </div>
                <?php endif; ?>

                <input type="hidden" name="default_billing" value="1">
                <input type="hidden" name="default_shipping" value="1">
            </fieldset>
        <?php endif; ?>
    <?php endif; ?>

    <fieldset class="fieldset create account"
              data-hasrequired="<?php echo $block->escapeHtml(__('* Required Fields')) ?>">
        <legend class="legend"><span><?php echo $block->escapeHtml(__('Sign-in Information')) ?></span></legend>
        <br>
        <div class="field required">
            <label for="email_address" class="label"><span><?php echo $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input type="email" name="email" autocomplete="email" id="email_address"
                       value="<?php echo $block->escapeHtml($block->getFormData()->getEmail()) ?>"
                       title="<?php echo $block->escapeHtml(__('Email')) ?>" class="input-text"
                       data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <div class="field password required" data-mage-init='{"passwordStrengthIndicator": {}}'>
            <label for="password" class="label"><span><?php echo $block->escapeHtml(__('Password')) ?></span></label>
            <div class="control">
                <input type="password" name="password" id="password"
                       title="<?php echo $block->escapeHtml(__('Password')) ?>"
                       class="input-text"
                       data-password-min-length="<?php echo $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                       data-password-min-character-sets="<?php echo $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                       data-validate="{required:true, 'validate-customer-password':true}"
                       autocomplete="off">
                <div id="password-strength-meter-container" data-role="password-strength-meter">
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?php echo $block->escapeHtml(__('Password Strength')); ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?php echo $block->escapeHtml(__('No Password')); ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="field confirmation required">
            <label for="password-confirmation"
                   class="label"><span><?php echo $block->escapeHtml(__('Confirm Password')) ?></span></label>
            <div class="control">
                <input type="password" name="password_confirmation"
                       title="<?php echo $block->escapeHtml(__('Confirm Password')) ?>" id="password-confirmation"
                       class="input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
            </div>
        </div>
        <?php echo $block->getChildHtml('form_additional_info'); ?>
    </fieldset>

    <?php echo $block->getChildHtml('aceextensions.form.additional.info'); ?>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary"
                    title="<?php echo $block->escapeHtml(__('Create an Account')) ?>">
                <span><?php echo $block->escapeHtml(__('Create an Account')) ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back"
               href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php echo $block->escapeHtml(__('Back')) ?></span></a>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
    "*": {
        "Aceextensions_B2bRegistration/js/validate": {}
        }
    }

</script>
<?php if ($block->getShowAddressFields()): ?>
    <script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php /* @escapeNotVerified */
        echo($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?php /* @escapeNotVerified */
        echo $block->getHelperDirectoryData()->getRegionJson() ?>,
                "defaultRegion": "<?php echo (int)$block->getFormData()->getRegionId() ?>",
                "countriesWithOptionalZip": <?php /* @escapeNotVerified */
        echo $block->getHelperDirectoryData()->getCountriesWithOptionalZip(true) ?>
            }
        }
    }

    </script>
<?php endif; ?>
